ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 124, in response_for_exception
    security_logger.error(
  File "/usr/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/log.py", line 125, in emit
    reporter.get_traceback_text(),
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 417, in get_traceback_text
    c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lsws/Example/html/dentist/dentist/urls.py", line 8, in <module>
    path('', include('website.urls')),
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lsws/Example/html/dentist/website/urls.py", line 4, in <module>
    from . import views
  File "/usr/local/lsws/Example/html/dentist/website/views.py", line 145, in <module>
    parse_rss_feed()
  File "/usr/local/lsws/Example/html/dentist/website/views.py", line 127, in parse_rss_feed
    print(f"Entry {i + 1} structure: {entry}")
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 101-102: ordinal not in range(128)
ERROR:django.request:Internal Server Error: /assets/video/news1.mp4
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 124, in response_for_exception
    security_logger.error(
  File "/usr/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/log.py", line 125, in emit
    reporter.get_traceback_text(),
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 417, in get_traceback_text
    c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lsws/Example/html/dentist/dentist/urls.py", line 8, in <module>
    path('', include('website.urls')),
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lsws/Example/html/dentist/website/urls.py", line 4, in <module>
    from . import views
  File "/usr/local/lsws/Example/html/dentist/website/views.py", line 145, in <module>
    parse_rss_feed()
  File "/usr/local/lsws/Example/html/dentist/website/views.py", line 127, in parse_rss_feed
    print(f"Entry {i + 1} structure: {entry}")
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode character '\u0131' in position 142: ordinal not in range(128)
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news3.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news1.mp4
ERROR:django.request:Internal Server Error: /assets/video/news3.mp4
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 124, in response_for_exception
    security_logger.error(
  File "/usr/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/log.py", line 125, in emit
    reporter.get_traceback_text(),
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 417, in get_traceback_text
    c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lsws/Example/html/dentist/dentist/urls.py", line 8, in <module>
    path('', include('website.urls')),
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lsws/Example/html/dentist/website/urls.py", line 4, in <module>
    from . import views
  File "/usr/local/lsws/Example/html/dentist/website/views.py", line 145, in <module>
    parse_rss_feed()
  File "/usr/local/lsws/Example/html/dentist/website/views.py", line 127, in parse_rss_feed
    print(f"Entry {i + 1} structure: {entry}")
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode character '\u0131' in position 142: ordinal not in range(128)
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news3.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news1.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news2.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news2.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news1.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news3.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news1.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news3.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news3.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news1.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news2.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news1.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news3.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news1.mp4
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /assets/video/news3.mp4
ERROR:django.request:Internal Server Error: /assets/video/news2.mp4
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 124, in response_for_exception
    security_logger.error(
  File "/usr/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/log.py", line 125, in emit
    reporter.get_traceback_text(),
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 417, in get_traceback_text
    c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lsws/Example/html/dentist/dentist/urls.py", line 8, in <module>
    path('', include('website.urls')),
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lsws/Example/html/dentist/website/urls.py", line 4, in <module>
    from . import views
  File "/usr/local/lsws/Example/html/dentist/website/views.py", line 145, in <module>
    parse_rss_feed()
  File "/usr/local/lsws/Example/html/dentist/website/views.py", line 127, in parse_rss_feed
    print(f"Entry {i + 1} structure: {entry}")
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode character '\u0131' in position 142: ordinal not in range(128)
ERROR:django.request:Internal Server Error: /assets/video/news1.mp4
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 124, in response_for_exception
    security_logger.error(
  File "/usr/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/log.py", line 125, in emit
    reporter.get_traceback_text(),
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 417, in get_traceback_text
    c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lsws/Example/html/dentist/dentist/urls.py", line 8, in <module>
    path('', include('website.urls')),
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lsws/Example/html/dentist/website/urls.py", line 4, in <module>
    from . import views
  File "/usr/local/lsws/Example/html/dentist/website/views.py", line 145, in <module>
    parse_rss_feed()
  File "/usr/local/lsws/Example/html/dentist/website/views.py", line 127, in parse_rss_feed
    print(f"Entry {i + 1} structure: {entry}")
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode character '\u0131' in position 142: ordinal not in range(128)
ERROR:django.request:Internal Server Error: /assets/video/news3.mp4
Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'kimdenduydun.com.tr'. You may need to add 'kimdenduydun.com.tr' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/core/handlers/exception.py", line 124, in response_for_exception
    security_logger.error(
  File "/usr/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/log.py", line 125, in emit
    reporter.get_traceback_text(),
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 417, in get_traceback_text
    c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lsws/Example/html/dentist/dentist/urls.py", line 8, in <module>
    path('', include('website.urls')),
  File "/usr/local/lsws/Example/html/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lsws/Example/html/dentist/website/urls.py", line 4, in <module>
    from . import views
  File "/usr/local/lsws/Example/html/dentist/website/views.py", line 145, in <module>
    parse_rss_feed()
  File "/usr/local/lsws/Example/html/dentist/website/views.py", line 127, in parse_rss_feed
    print(f"Entry {i + 1} structure: {entry}")
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode character '\u0131' in position 142: ordinal not in range(128)
